// <auto-generated />
using System;
using ContactManager.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactManager.SqliteMigrations
{
    [DbContext(typeof(SQLiteContactManagerDbContext))]
    [Migration("20220828204818_AddSeedData")]
    partial class AddSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("ContactManager.DTOs.CompanyVendorDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyName")
                        .IsUnique();

                    b.HasIndex("VendorCode")
                        .IsUnique();

                    b.ToTable("VendorMasterList");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d56bdab0-bed0-4983-a80f-390a641a8376"),
                            CompanyName = "ACME Acids",
                            VendorCode = "A001"
                        },
                        new
                        {
                            Id = new Guid("eb7619b2-11b4-4780-9a3f-dda3ab10f1ed"),
                            CompanyName = "Berenstain Biology",
                            VendorCode = "A002"
                        },
                        new
                        {
                            Id = new Guid("a11c0b31-5833-4df5-b57a-dbad990934d9"),
                            CompanyName = "Flick’s Fluidics",
                            VendorCode = "A003"
                        },
                        new
                        {
                            Id = new Guid("67e0b7da-0c37-47ea-bad4-d7654ca90205"),
                            CompanyName = "Radical Reagents",
                            VendorCode = "D004"
                        },
                        new
                        {
                            Id = new Guid("7d64d5e9-c21a-4170-8509-c86c16390df9"),
                            CompanyName = "BBST Paper Products",
                            VendorCode = "G065"
                        });
                });

            modelBuilder.Entity("ContactManager.DTOs.CustomerDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a8886244-3763-4a53-bcb1-12eb3220db51"),
                            Address = "1 Amphitheater Parkway, Mountain View, CA",
                            Company = "Google",
                            Name = "Scottie Scheffler",
                            Notes = "Interested in ddPCR.",
                            Phone = "(510)555-3282"
                        },
                        new
                        {
                            Id = new Guid("62e66cb8-a6b9-4a97-92cf-8569fc7493a0"),
                            Address = "3555 Farnam Street, Omaha, NE",
                            Company = "Berkshire Hathaway",
                            Name = "Warren Buffett",
                            Notes = "Deep pockets.",
                            Phone = "(510)555-8164"
                        },
                        new
                        {
                            Id = new Guid("a8ed1a80-943c-4745-aa10-3d2b8561f2b9"),
                            Address = "13101 Harold Green Road, Austin, Texas",
                            Company = "Tesla",
                            Name = "Elon Musk",
                            Notes = "Also deep pockets.",
                            Phone = "(510)555-8912"
                        });
                });

            modelBuilder.Entity("ContactManager.DTOs.VendorDTO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Vendor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ff1926fb-30f1-4d44-aea9-fa82d1e120cf"),
                            Address = "111 A Street, Benicia, CA",
                            Company = "Radical Reagents",
                            Name = "George W. Salesman",
                            Phone = "(510)555-1234"
                        },
                        new
                        {
                            Id = new Guid("a8864005-ce08-4983-b3c4-4b16d132a5ae"),
                            Address = "222 B Street, Benicia, CA",
                            Company = "Berenstain Biology",
                            Name = "Stephanie Saleswoman",
                            Phone = "(510)555-3289"
                        },
                        new
                        {
                            Id = new Guid("3c07c8ff-ebb3-454d-b86d-d6b7a98b599c"),
                            Address = "333 C Street, Benicia, CA",
                            Company = "ACME Acids",
                            Name = "Jane Doe",
                            Phone = "(510)555-5439"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
